const ShowInfoTypes = {
    FETCH_SHOW_INFO_START:'FETCH_SHOW_INFO_START',
    FETCH_SHOW_INFO_SUCCESS:'FETCH_SHOW_INFO_SUCCESS',
    FETCH_SHOW_INFO_FAILURE:'FETCH_SHOW_INFO_FAILURE',
    SELECT_BY_PAGE_NUMBER:'SELECT_BY_PAGE_NUMBER',
}

export default ShowInfoTypes;